import GetFromShuffled from '../utils/GetFromShuffled';

export default GetFromShuffled([
  `23andMe results`,
  `adoption`,
  `Amazon reviews`,
  `apocalypse`,
  `biological clock`,
  `cancer`,
  `disinheritance`,
  `eating disorder`,
  `family secrets`,
  `father's murder`,
  `fear of spiders`,
  `feminism`,
  `mother's death`,
  `Oedipal complex`,
  `own birth`,
  `political apathy`,
  `privilege`,
  `religious upbringing`,
  `social media addiction`,
  `spiritual evolution`,
  `secret second family`,
  `sexual awakening`,
  `sexless marriage`,
  `traumatic childhood`,
  `toxic friendships`,
  `ugly divorce`,
  `untimely death`,
  `writer's block`,
]);
