import GetFromShuffled from '../utils/GetFromShuffled';

export default GetFromShuffled([
  `adolescent`,
  `adventurer`,
  `child`,
  `couple`,
  `coven`,
  `daughter`,
  `dictator`,
  `divorcée`,
  `doctor`,
  `extended family`,
  `ghost`,
  `man`,
  `mistress`,
  `mother`,
  `murder detective`,
  `octogenarian`,
  `orphan`,
  `private investigator`,
  `professor`,
  `soldier`,
  `starship captain`,
  `student`,
  `vampire`,
  `widow`,
  `woman`,
  `writer`,
])
