import GetFromShuffled from '../utils/GetFromShuffled';

export default GetFromShuffled([
  "man",
  "orphan",
  "daughter",
  "mother",
  "adolescent",
  "soldier",
  "student",
  "widow",
  "woman",
  "professor",
  "divorcée",
  "adventurer",
  "extended family",
  "child",
  "mistress",
  "dictator",
  "vampire",
  "ghost",
  "starship captain",
  "doctor",
  "writer",
  "private investigator",
  "couple",
  "coven",
  "murder detective",
  "octogenarian"
]);
