import GetFromShuffled from '../utils/GetFromShuffled';

export default GetFromShuffled([
  `agoraphobic`,
  `alcoholic`,
  `bored`,
  `closeted`,
  `depressed`,
  `desperate`,
  `dissatisfied`,
  `doomed`,
  `drug-addled`,
  `exuberant`,
  `hopelessly romantic`,
  `hyper-sexual`,
  `jilted`,
  `lovesick`,
  `maladjusted`,
  `misanthropic`,
  `morally compromised`,
  `overbearing`,
  `philosophical`,
  `precocious`,
  `quixotic`,
  `refugee`,
  `unlucky`,
  `vengeful`,
  `wealthy`,
  `young`,
])
